# Generated by Django 2.2.1 on 2019-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDeAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Título')),
                ('description', models.CharField(max_length=80, verbose_name='Descrição rápida')),
                ('text', models.TextField(verbose_name='Texto sobre a área')),
                ('image', models.ImageField(blank=True, null=True, upload_to='area_atuacao/', verbose_name='Imagem')),
                ('order', models.IntegerField(verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name_plural': 'Áreas de atuação',
                'ordering': ['order', 'title'],
                'verbose_name': 'Área de atuação',
            },
        ),
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('curriculum', models.CharField(blank=True, max_length=260, null=True, verbose_name='Currículo')),
                ('image', models.ImageField(upload_to='associado/', verbose_name='Imagem')),
                ('order', models.IntegerField(verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name_plural': 'Associados',
                'ordering': ['order', 'name'],
                'verbose_name': 'Associado',
            },
        ),
    ]
