# Generated by Django 2.2.1 on 2019-06-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto sobre a empresa')),
            ],
            options={
                'verbose_name': 'Institucional',
                'verbose_name_plural': 'Institucional',
            },
        ),
    ]
